---
title: "Lentil Phenology"
subtitle: "**Understanding photothermal interactions can help expand production range and increase genetic diversity of lentil (*Lens culinaris* Medik.)**. *Plants, People, Planet*. (2020) 00: 1-11."
summary:  "**Understanding photothermal interactions can help expand production range and increase genetic diversity of lentil (*Lens culinaris* Medik.)**. *Plants, People, Planet*. (2020) 00: 1-11."
date: "`r Sys.Date()`"
author: "Derek Michael Wright <derek.wright@usask.ca> [www.dblogr.com/](https://dblogr.com/#posts_academic)"
tags: [ "Publications", "AGILE", "Lentil", "Phenomics", "Phenology", "Featured" ]
weight: 1
links:
  - icon: "newspaper"
    icon_pack: "far"
    name: "Plants, People, Planet. (2020) 00: 1-11."
    url: "https://doi.org/10.1002/ppp3.10158"
  - icon: "github"
    icon_pack: "fab"
    name: "Github Repository"
    url: "https://github.com/derekmichaelwright/AGILE_LDP_Phenology"
  - icon: "save"
    icon_pack: "fa"
    name: "Data"
    url: "https://github.com/derekmichaelwright/AGILE_LDP_Phenology/tree/master/data"
  - icon: "chart-line"
    icon_pack: "fas"
    name: "All Figures (HTML)"
    url: "https://derekmichaelwright.github.io/AGILE_LDP_Phenology/README.html"
  - icon: "file-pdf"
    icon_pack: "far"
    name: "All Figures (pdf)"
    url: "https://github.com/derekmichaelwright/AGILE_LDP_Phenology/blob/master/README.pdf"
  - icon: "r-project"
    icon_pack: "fab"
    name: "R Script (HTML)"
    url: "https://derekmichaelwright.github.io/AGILE_LDP_Phenology/Phenology_Vignette.html"
  - icon: "laptop-code"
    icon_pack: "fas"
    name: "AGILE_LDP_Phenology (Shiny App)"
    url: "https://derek-wright-usask.shinyapps.io/AGILE_LDP_Phenology/"
  - icon: "laptop-code"
    icon_pack: "fas"
    name: "Predict DTF (Shiny App)"
    url: "https://derek-wright-usask.shinyapps.io/AGILE_Predict_DTF/"
external_link: "https://doi.org/10.1002/ppp3.10158"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

---

# Citation

Wright, D.M., Neupane, S., Heidecker, T., Haile, T.A., Chan, C., Coyne, C.J., McGee, R.J., Udupa, S., Henkrar, F., Barilli, E., Rubiales, D., Gioia, T., Logozzo, G., Marzario, S., Mehra, R., Sarker, A., Dhakal, R., Anwar, B., Sarker, D., Vandenberg A. & Bett K.E. (2020) **Understanding photothermal interactions can help expand production range and increase genetic diversity of lentil (*Lens culinaris* Medik.)**. *Plants, People, Planet*. 00: 1-11. https://doi.org/10.1002/ppp3.10158

---

# Abstract

## Societal Impact Statement

Lentil is a staple in many diets around the world and growing in popularity as a quick‐cooking, nutritious, plant‐based source of protein in the human diet. Lentil varieties are usually grown close to where they were bred. Future climate change scenarios will result in increased temperatures and shifts in lentil crop production areas, necessitating expanded breeding efforts. We show how we can use a daylength and temperature model to identify varieties most likely to succeed in these new environments, expand genetic diversity, and give plant breeders additional knowledge and tools to help mitigate these changes for lentil producers.

## Summary

- Lentil (Lens culinaris Medik.) is cultivated under a wide range of environmental conditions, which has led to diverse phenological adaptations and resulted in a decrease in genetic variability within breeding programs due to reluctance in using genotypes from other environments.
- We phenotyped 324 genotypes across nine locations over three years to assess their phenological response to the environment of major lentil production regions and to predict days from sowing to flowering (DTF) using a photothermal model.
-DTF was highly influenced by the environment and is sufficient to explain adaptation. We were able to predict DTF reliably in most environments using a simple photothermal model, however, in certain site‐years, results suggest there may be additional environmental factors at play. Hierarchical clustering of principal components revealed the presence of eight groups based on the responses of DTF to contrasting environments. These groups are associated with the coefficients of the photothermal model and revealed differences in temperature and photoperiod sensitivity.
- Future climate change scenarios will result in increased temperature and/or shifts in production areas. The ability to use the photothermal model to identify genotypes most likely to succeed in these new environments has important social impacts with respect to traditional cropping systems.

---

# LDP Origins

https://derekmichaelwright.github.io/AGILE_LDP_Phenology/Additional/Additional_Figure_09.html

<iframe
  src="https://derekmichaelwright.github.io/AGILE_LDP_Phenology/Additional/Additional_Figure_09.html"
  style="width:100%; height:600px; align:center;"
></iframe>

---

Derek Michael Wright [www.dblogr.com/](https://dblogr.com/)