---
output:
  pagedown::html_resume: 
    self_contained: yes
---

Aside
====================================

**Derek M. Wright** {#contact}
--------------------------------------------------------------------------------

<br>

### <i class="fa fa-address-card"></i> Contact Info {#contact}

- <i class="fa fa-envelope"></i> &nbsp; wrightmderek@gmail.com
- <i class="fa fa-envelope-o"></i> &nbsp; derek.wright@usask.ca
- <i class="fa fa-phone"></i> &nbsp; +1 306-220-0645

### <i class="fa fa-cloud"></i> Social Media

- <i class="fa fa-twitter-square"></i> &nbsp; [@DerekMWright](https://twitter.com/DerekMWright)
- <i class="fa fa-github"></i> &nbsp; [github.com/derekmichaelwright](https://github.com/derekmichaelwright)

### <i class="fa fa-globe"></i> Personal Website

[www.dblogr.com/](http://dblogr.com/) or 

[derekmichaelwright.github.io/dblogr/](https://derekmichaelwright.github.io/dblogr/)

Main
================================================================================

Research Assistant, Mustard breeding {#title}
--------------------------------------------------------------------------------

2023-05-18

<br>

Dear Amanda Leblanc,

Please accept my application for the position of Research Assistant, Mustard breeding. I am excited to be considered for this role and believe I would be a good candidate. I have a BSc in Biology from the University of Regina, a MSc in Agrobiotechnology from Justus-Liebig-Universität Gießen (University of Giessen) and have spent the last 6+ years at the University of Saskatchewan as a Research Assistant in the pulse crop breeding & genetics group working with lentils. I also have experience working with Brassica crops for my MSc and during an internship I did with Cargil. 

For the last 6+ years I have been in charge of field trials for various lentil populations including a diversity panel, a nested association panel and numerous inter-specific RIL populations. My duties included planning of the field trial set-up, seed preparation, phenotyping, harvest and post-harvest processing, along with the data wrangling and analyses. I was also responsible for coordinating the import and export of seed for our international field trials.

In addition to overseeing our field trials, I have extensive experience in wrangling very large data sets and performing complex statistical procedures such as GWAS and QTL analyses. I am very comfortable working in <i class="fab fa-r-project"></i> and have a passion for data visualization. My most recent work involved utilizing UAV imagery to model growth curves for a lentil diversity panel across multi-environment trials and perform GWAS on novel traits derived from the analysis.

I am confident my knowledge and experience in plant breeding and research will make me a good fit for this position. Thank you for your consideration, and I hope to hear from you soon.

<br>

Sincerely, 

Derek Michael Wright
