---
title: "R Tutorial Vignette"
subtitle: "An introduction to R"
summary:  "An introduction to R"
date: "2021-07-01"
author: "Derek Michael Wright <derek.wright@usask.ca> [www.dblogr.com/](https://dblogr.com/academic/r_tutorial)"
tags: [ "Academic", "AGILE", "Tutorial", "Featured" ]
weight: 1
codefolding_show: "show"
image:
  preview_only: true
links:
  - icon: "file-code"
    icon_pack: "far"
    name: "HTML < R Script Vignette >"
    url: "https://derekmichaelwright.github.io/htmls/academic/r_tutorial.html"
output:
  blogdown::html_page:
    toc: true
---

<script src="{{< blogdown/postref >}}index_files/htmlwidgets/htmlwidgets.js"></script>
<script src="{{< blogdown/postref >}}index_files/jquery/jquery.min.js"></script>
<link href="{{< blogdown/postref >}}index_files/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/datatables-binding/datatables.js"></script>
<link href="{{< blogdown/postref >}}index_files/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="{{< blogdown/postref >}}index_files/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/dt-core/js/jquery.dataTables.min.js"></script>
<link href="{{< blogdown/postref >}}index_files/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="{{< blogdown/postref >}}index_files/crosstalk/js/crosstalk.min.js"></script>

<div id="TOC">
<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#download-r">Download R</a></li>
<li><a href="#calculator">Calculator</a></li>
<li><a href="#functions">Functions</a></li>
<li><a href="#objects">Objects</a></li>
<li><a href="#data-formats">Data Formats</a></li>
<li><a href="#packages">Packages</a></li>
<li><a href="#data-wrangling">Data Wrangling</a></li>
<li><a href="#readwrite-data">Read/Write data</a></li>
<li><a href="#tidy-data">Tidy Data</a></li>
<li><a href="#base-plotting">Base Plotting</a></li>
<li><a href="#ggplot2">ggplot2</a></li>
<li><a href="#statistics">Statistics</a></li>
<li><a href="#pch-plot">pch Plot</a></li>
<li><a href="#r-markdown">R Markdown</a></li>
</ul>
</div>

<hr />
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This vignette will introduce the reader to <code>R</code>, a free, open-source statistical computing environment and <code>RStudio</code>, a integrated development environment for <code>R</code>.</p>
<p><img src="logo_r.png" style="width:25.0%" /></p>
<hr />
</div>
<div id="download-r" class="section level1">
<h1>Download R</h1>
<p><a href="https://www.r-project.org/">Download R</a></p>
<p><a href="https://rstudio.com/products/rstudio/download/">Download RStudio</a></p>
<p><img src="rstudio.png" /></p>
<p><a href="http://r-statistics.co/R-Tutorial.html" class="uri">http://r-statistics.co/R-Tutorial.html</a></p>
<p><a href="https://bookdown.org/rdpeng/exdata/getting-started-with-r.html#installation" class="uri">https://bookdown.org/rdpeng/exdata/getting-started-with-r.html#installation</a></p>
<hr />
</div>
<div id="calculator" class="section level1">
<h1>Calculator</h1>
<p>R can be used as a super awesome calculator</p>
<pre class="r"><code># 5 + 3 = 8
5 + 3 </code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code># 24 / (1 + 2) = 8
24 / (1 + 2) </code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code># 2 * 2 * 2 = 8
2^3 </code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code># 8 * 8 = 64
sqrt(64) </code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="r"><code># -log10(0.05 / 5000000) = 8
-log10(0.05 / 5000000) </code></pre>
<pre><code>## [1] 8</code></pre>
<hr />
</div>
<div id="functions" class="section level1">
<h1>Functions</h1>
<p>R has many useful built in functions</p>
<pre class="r"><code>1:10</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<pre class="r"><code>as.character(1:10)</code></pre>
<pre><code>##  [1] &quot;1&quot;  &quot;2&quot;  &quot;3&quot;  &quot;4&quot;  &quot;5&quot;  &quot;6&quot;  &quot;7&quot;  &quot;8&quot;  &quot;9&quot;  &quot;10&quot;</code></pre>
<pre class="r"><code>rep(1:2, times = 5)</code></pre>
<pre><code>##  [1] 1 2 1 2 1 2 1 2 1 2</code></pre>
<pre class="r"><code>rep(1:5, times = 2)</code></pre>
<pre><code>##  [1] 1 2 3 4 5 1 2 3 4 5</code></pre>
<pre class="r"><code>rep(1:5, each = 2)</code></pre>
<pre><code>##  [1] 1 1 2 2 3 3 4 4 5 5</code></pre>
<pre class="r"><code>rep(1:5, length.out = 7)</code></pre>
<pre><code>## [1] 1 2 3 4 5 1 2</code></pre>
<pre class="r"><code>help(rep)
seq(5, 50, by = 5)</code></pre>
<pre><code>##  [1]  5 10 15 20 25 30 35 40 45 50</code></pre>
<pre class="r"><code>seq(5, 50, length.out = 5)</code></pre>
<pre><code>## [1]  5.00 16.25 27.50 38.75 50.00</code></pre>
<pre class="r"><code>paste(1:10, 20:30, sep = &quot;-&quot;)</code></pre>
<pre><code>##  [1] &quot;1-20&quot;  &quot;2-21&quot;  &quot;3-22&quot;  &quot;4-23&quot;  &quot;5-24&quot;  &quot;6-25&quot;  &quot;7-26&quot;  &quot;8-27&quot;  &quot;9-28&quot; 
## [10] &quot;10-29&quot; &quot;1-30&quot;</code></pre>
<pre class="r"><code>paste(1:10, collapse = &quot;-&quot;)</code></pre>
<pre><code>## [1] &quot;1-2-3-4-5-6-7-8-9-10&quot;</code></pre>
<pre class="r"><code>paste0(&quot;x&quot;, 1:10)</code></pre>
<pre><code>##  [1] &quot;x1&quot;  &quot;x2&quot;  &quot;x3&quot;  &quot;x4&quot;  &quot;x5&quot;  &quot;x6&quot;  &quot;x7&quot;  &quot;x8&quot;  &quot;x9&quot;  &quot;x10&quot;</code></pre>
<pre class="r"><code>min(1:10)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>max(1:10)</code></pre>
<pre><code>## [1] 10</code></pre>
<pre class="r"><code>range(1:10)</code></pre>
<pre><code>## [1]  1 10</code></pre>
<pre class="r"><code>mean(1:10)</code></pre>
<pre><code>## [1] 5.5</code></pre>
<pre class="r"><code>sd(1:10)</code></pre>
<pre><code>## [1] 3.02765</code></pre>
<p>Users can also create their own functions</p>
<pre class="r"><code>customFunction1 &lt;- function(x, y) {
  z &lt;- 100 * x / (x + y)
  paste(z, &quot;%&quot;)
}
customFunction1(x = 10, y = 90)</code></pre>
<pre><code>## [1] &quot;10 %&quot;</code></pre>
<pre class="r"><code>customFunction2 &lt;- function(x) {
  mymin &lt;- mean(x - sd(x))
  mymax &lt;- mean(x) + sd(x)
  print(paste(&quot;Min =&quot;, mymin))
  print(paste(&quot;Max =&quot;, mymax))
}
customFunction2(x = 1:10)</code></pre>
<pre><code>## [1] &quot;Min = 2.47234964590251&quot;
## [1] &quot;Max = 8.52765035409749&quot;</code></pre>
<p><code>for</code> loops and <code>if</code> <code>else</code> statements</p>
<pre class="r"><code>xx &lt;- NULL #creates and empty object
for(i in 1:10) {
  xx[i] &lt;- i*3
}
xx</code></pre>
<pre><code>##  [1]  3  6  9 12 15 18 21 24 27 30</code></pre>
<pre class="r"><code>xx %% 2 #gives the remainder when divided by 2</code></pre>
<pre><code>##  [1] 1 0 1 0 1 0 1 0 1 0</code></pre>
<pre class="r"><code>for(i in 1:length(xx)) {
  if((xx[i] %% 2) == 0) {
    print(paste(xx[i],&quot;is Even&quot;))
  } else { 
      print(paste(xx[i],&quot;is Odd&quot;)) 
    }
}</code></pre>
<pre><code>## [1] &quot;3 is Odd&quot;
## [1] &quot;6 is Even&quot;
## [1] &quot;9 is Odd&quot;
## [1] &quot;12 is Even&quot;
## [1] &quot;15 is Odd&quot;
## [1] &quot;18 is Even&quot;
## [1] &quot;21 is Odd&quot;
## [1] &quot;24 is Even&quot;
## [1] &quot;27 is Odd&quot;
## [1] &quot;30 is Even&quot;</code></pre>
<pre class="r"><code># or
ifelse(xx %% 2 == 0, &quot;Even&quot;, &quot;Odd&quot;)</code></pre>
<pre><code>##  [1] &quot;Odd&quot;  &quot;Even&quot; &quot;Odd&quot;  &quot;Even&quot; &quot;Odd&quot;  &quot;Even&quot; &quot;Odd&quot;  &quot;Even&quot; &quot;Odd&quot;  &quot;Even&quot;</code></pre>
<pre class="r"><code>paste(xx, ifelse(xx %% 2 == 0, &quot;is Even&quot;, &quot;is Odd&quot;))</code></pre>
<pre><code>##  [1] &quot;3 is Odd&quot;   &quot;6 is Even&quot;  &quot;9 is Odd&quot;   &quot;12 is Even&quot; &quot;15 is Odd&quot; 
##  [6] &quot;18 is Even&quot; &quot;21 is Odd&quot;  &quot;24 is Even&quot; &quot;27 is Odd&quot;  &quot;30 is Even&quot;</code></pre>
<hr />
</div>
<div id="objects" class="section level1">
<h1>Objects</h1>
<p>Information can be stored in user defined objects, in multiple forms:</p>
<ul>
<li><code>c()</code>: a string of values</li>
<li><code>matrix()</code>: a two dimensional matrix in one format</li>
<li><code>data.frame()</code>: a two dimensional matrix where each column can be a different format</li>
<li><code>list()</code>:</li>
</ul>
<p>A string…</p>
<pre class="r"><code>xc &lt;- 1:10
xc</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<pre class="r"><code>xc &lt;- c(1,2,3,4,5,6,7,8,9,10)
xc</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<p>A matrix…</p>
<pre class="r"><code>xm &lt;- matrix(1:100, nrow = 10, ncol = 10, byrow = T)
xm</code></pre>
<pre><code>##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    1    2    3    4    5    6    7    8    9    10
##  [2,]   11   12   13   14   15   16   17   18   19    20
##  [3,]   21   22   23   24   25   26   27   28   29    30
##  [4,]   31   32   33   34   35   36   37   38   39    40
##  [5,]   41   42   43   44   45   46   47   48   49    50
##  [6,]   51   52   53   54   55   56   57   58   59    60
##  [7,]   61   62   63   64   65   66   67   68   69    70
##  [8,]   71   72   73   74   75   76   77   78   79    80
##  [9,]   81   82   83   84   85   86   87   88   89    90
## [10,]   91   92   93   94   95   96   97   98   99   100</code></pre>
<pre class="r"><code>xm &lt;- matrix(1:100, nrow = 10, ncol = 10, byrow = F)
xm</code></pre>
<pre><code>##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    1   11   21   31   41   51   61   71   81    91
##  [2,]    2   12   22   32   42   52   62   72   82    92
##  [3,]    3   13   23   33   43   53   63   73   83    93
##  [4,]    4   14   24   34   44   54   64   74   84    94
##  [5,]    5   15   25   35   45   55   65   75   85    95
##  [6,]    6   16   26   36   46   56   66   76   86    96
##  [7,]    7   17   27   37   47   57   67   77   87    97
##  [8,]    8   18   28   38   48   58   68   78   88    98
##  [9,]    9   19   29   39   49   59   69   79   89    99
## [10,]   10   20   30   40   50   60   70   80   90   100</code></pre>
<p>A data frame…</p>
<pre class="r"><code>xd &lt;- data.frame(
  x1 = c(&quot;aa&quot;,&quot;bb&quot;,&quot;cc&quot;,&quot;dd&quot;,&quot;ee&quot;,
         &quot;ff&quot;,&quot;gg&quot;,&quot;hh&quot;,&quot;ii&quot;,&quot;jj&quot;),
  x2 = 1:10,
  x3 = c(1,1,1,1,1,2,2,2,3,3),
  x4 = rep(c(1,2), times = 5),
  x5 = rep(1:5, times = 2),
  x6 = rep(1:5, each = 2),
  x7 = seq(5, 50, by = 5),
  x8 = log10(1:10),
  x9 = (1:10)^3,
  x10 = c(T,T,T,F,F,T,T,F,F,F)
)
xd</code></pre>
<pre><code>##    x1 x2 x3 x4 x5 x6 x7        x8   x9   x10
## 1  aa  1  1  1  1  1  5 0.0000000    1  TRUE
## 2  bb  2  1  2  2  1 10 0.3010300    8  TRUE
## 3  cc  3  1  1  3  2 15 0.4771213   27  TRUE
## 4  dd  4  1  2  4  2 20 0.6020600   64 FALSE
## 5  ee  5  1  1  5  3 25 0.6989700  125 FALSE
## 6  ff  6  2  2  1  3 30 0.7781513  216  TRUE
## 7  gg  7  2  1  2  4 35 0.8450980  343  TRUE
## 8  hh  8  2  2  3  4 40 0.9030900  512 FALSE
## 9  ii  9  3  1  4  5 45 0.9542425  729 FALSE
## 10 jj 10  3  2  5  5 50 1.0000000 1000 FALSE</code></pre>
<p>A list…</p>
<pre class="r"><code>xl &lt;- list(xc, xm, xd)
xl[[1]]</code></pre>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<pre class="r"><code>xl[[2]]</code></pre>
<pre><code>##       [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
##  [1,]    1   11   21   31   41   51   61   71   81    91
##  [2,]    2   12   22   32   42   52   62   72   82    92
##  [3,]    3   13   23   33   43   53   63   73   83    93
##  [4,]    4   14   24   34   44   54   64   74   84    94
##  [5,]    5   15   25   35   45   55   65   75   85    95
##  [6,]    6   16   26   36   46   56   66   76   86    96
##  [7,]    7   17   27   37   47   57   67   77   87    97
##  [8,]    8   18   28   38   48   58   68   78   88    98
##  [9,]    9   19   29   39   49   59   69   79   89    99
## [10,]   10   20   30   40   50   60   70   80   90   100</code></pre>
<pre class="r"><code>xl[[3]]</code></pre>
<pre><code>##    x1 x2 x3 x4 x5 x6 x7        x8   x9   x10
## 1  aa  1  1  1  1  1  5 0.0000000    1  TRUE
## 2  bb  2  1  2  2  1 10 0.3010300    8  TRUE
## 3  cc  3  1  1  3  2 15 0.4771213   27  TRUE
## 4  dd  4  1  2  4  2 20 0.6020600   64 FALSE
## 5  ee  5  1  1  5  3 25 0.6989700  125 FALSE
## 6  ff  6  2  2  1  3 30 0.7781513  216  TRUE
## 7  gg  7  2  1  2  4 35 0.8450980  343  TRUE
## 8  hh  8  2  2  3  4 40 0.9030900  512 FALSE
## 9  ii  9  3  1  4  5 45 0.9542425  729 FALSE
## 10 jj 10  3  2  5  5 50 1.0000000 1000 FALSE</code></pre>
<p>Selecting data…</p>
<pre class="r"><code>xc[5] # 5th element in xc</code></pre>
<pre><code>## [1] 5</code></pre>
<pre class="r"><code>xd$x3[5] # 5th element in col &quot;x3&quot;</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>xd[5,&quot;x3&quot;] # row 5, col &quot;x3&quot;</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>xd$x3 # all of col &quot;x3&quot;</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 3 3</code></pre>
<pre class="r"><code>xd[,&quot;x3&quot;] # all rows, col &quot;x3&quot;</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 3 3</code></pre>
<pre class="r"><code>xd[3,] # row 3, all cols</code></pre>
<pre><code>##   x1 x2 x3 x4 x5 x6 x7        x8 x9  x10
## 3 cc  3  1  1  3  2 15 0.4771213 27 TRUE</code></pre>
<pre class="r"><code>xd[c(2,4),c(&quot;x4&quot;,&quot;x5&quot;)] # rows 2 &amp; 4, cols &quot;x4&quot; &amp; &quot;x5&quot;</code></pre>
<pre><code>##   x4 x5
## 2  2  2
## 4  2  4</code></pre>
<pre class="r"><code>xl[[3]]$x1 # 3rd object in the list, col &quot;x1</code></pre>
<pre><code>##  [1] &quot;aa&quot; &quot;bb&quot; &quot;cc&quot; &quot;dd&quot; &quot;ee&quot; &quot;ff&quot; &quot;gg&quot; &quot;hh&quot; &quot;ii&quot; &quot;jj&quot;</code></pre>
<hr />
</div>
<div id="data-formats" class="section level1">
<h1>Data Formats</h1>
<p>Data can also be saved in many formats:</p>
<ul>
<li>numeric</li>
<li>integer</li>
<li>character</li>
<li>factor</li>
<li>logical</li>
</ul>
<pre class="r"><code>xd$x3 &lt;- as.character(xd$x3)
xd$x3</code></pre>
<pre><code>##  [1] &quot;1&quot; &quot;1&quot; &quot;1&quot; &quot;1&quot; &quot;1&quot; &quot;2&quot; &quot;2&quot; &quot;2&quot; &quot;3&quot; &quot;3&quot;</code></pre>
<pre class="r"><code>xd$x3 &lt;- as.numeric(xd$x3)
xd$x3</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 3 3</code></pre>
<pre class="r"><code>xd$x3 &lt;- as.factor(xd$x3)
xd$x3</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 3 3
## Levels: 1 2 3</code></pre>
<pre class="r"><code>xd$x3 &lt;- factor(xd$x3, levels = c(&quot;3&quot;,&quot;2&quot;,&quot;1&quot;))
xd$x3</code></pre>
<pre><code>##  [1] 1 1 1 1 1 2 2 2 3 3
## Levels: 3 2 1</code></pre>
<pre class="r"><code>xd$x10</code></pre>
<pre><code>##  [1]  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE</code></pre>
<pre class="r"><code>as.numeric(xd$x10) # TRUE = 1, FALSE = 0</code></pre>
<pre><code>##  [1] 1 1 1 0 0 1 1 0 0 0</code></pre>
<pre class="r"><code>sum(xd$x10)</code></pre>
<pre><code>## [1] 5</code></pre>
<p>Internal structure of an object can be checked with <code>str()</code></p>
<pre class="r"><code>str(xc) # c()</code></pre>
<pre><code>##  num [1:10] 1 2 3 4 5 6 7 8 9 10</code></pre>
<pre class="r"><code>str(xm) # matrix()</code></pre>
<pre><code>##  int [1:10, 1:10] 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
<pre class="r"><code>str(xd) # data.frame()</code></pre>
<pre><code>## &#39;data.frame&#39;:    10 obs. of  10 variables:
##  $ x1 : chr  &quot;aa&quot; &quot;bb&quot; &quot;cc&quot; &quot;dd&quot; ...
##  $ x2 : int  1 2 3 4 5 6 7 8 9 10
##  $ x3 : Factor w/ 3 levels &quot;3&quot;,&quot;2&quot;,&quot;1&quot;: 3 3 3 3 3 2 2 2 1 1
##  $ x4 : num  1 2 1 2 1 2 1 2 1 2
##  $ x5 : int  1 2 3 4 5 1 2 3 4 5
##  $ x6 : int  1 1 2 2 3 3 4 4 5 5
##  $ x7 : num  5 10 15 20 25 30 35 40 45 50
##  $ x8 : num  0 0.301 0.477 0.602 0.699 ...
##  $ x9 : num  1 8 27 64 125 216 343 512 729 1000
##  $ x10: logi  TRUE TRUE TRUE FALSE FALSE TRUE ...</code></pre>
<pre class="r"><code>str(xl) # list()</code></pre>
<pre><code>## List of 3
##  $ : num [1:10] 1 2 3 4 5 6 7 8 9 10
##  $ : int [1:10, 1:10] 1 2 3 4 5 6 7 8 9 10 ...
##  $ :&#39;data.frame&#39;:    10 obs. of  10 variables:
##   ..$ x1 : chr [1:10] &quot;aa&quot; &quot;bb&quot; &quot;cc&quot; &quot;dd&quot; ...
##   ..$ x2 : int [1:10] 1 2 3 4 5 6 7 8 9 10
##   ..$ x3 : num [1:10] 1 1 1 1 1 2 2 2 3 3
##   ..$ x4 : num [1:10] 1 2 1 2 1 2 1 2 1 2
##   ..$ x5 : int [1:10] 1 2 3 4 5 1 2 3 4 5
##   ..$ x6 : int [1:10] 1 1 2 2 3 3 4 4 5 5
##   ..$ x7 : num [1:10] 5 10 15 20 25 30 35 40 45 50
##   ..$ x8 : num [1:10] 0 0.301 0.477 0.602 0.699 ...
##   ..$ x9 : num [1:10] 1 8 27 64 125 216 343 512 729 1000
##   ..$ x10: logi [1:10] TRUE TRUE TRUE FALSE FALSE TRUE ...</code></pre>
<hr />
</div>
<div id="packages" class="section level1">
<h1>Packages</h1>
<p>Additional libraries can be installed and loaded for use.</p>
<pre class="r"><code>install.packages(&quot;scales&quot;)</code></pre>
<pre class="r"><code>library(scales)
xx &lt;- data.frame(Values = 1:10)
xx$Rescaled &lt;- rescale(x = xx$Values, to = c(1,30))
xx</code></pre>
<pre><code>##    Values  Rescaled
## 1       1  1.000000
## 2       2  4.222222
## 3       3  7.444444
## 4       4 10.666667
## 5       5 13.888889
## 6       6 17.111111
## 7       7 20.333333
## 8       8 23.555556
## 9       9 26.777778
## 10     10 30.000000</code></pre>
<hr />
</div>
<div id="data-wrangling" class="section level1">
<h1>Data Wrangling</h1>
<p><a href="https://r4ds.had.co.nz/">R for Data Science</a></p>
<pre class="r"><code>xx &lt;- data.frame(Group = c(&quot;X&quot;,&quot;X&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;X&quot;,&quot;X&quot;,&quot;X&quot;,&quot;Y&quot;,&quot;Y&quot;),
                 Data1 = 1:10, 
                 Data2 = seq(10, 100, by = 10))
xx$NewData1 &lt;- xx$Data1 + xx$Data2
xx$NewData2 &lt;- xx$Data1 * 1000
xx</code></pre>
<pre><code>##    Group Data1 Data2 NewData1 NewData2
## 1      X     1    10       11     1000
## 2      X     2    20       22     2000
## 3      Y     3    30       33     3000
## 4      Y     4    40       44     4000
## 5      Y     5    50       55     5000
## 6      X     6    60       66     6000
## 7      X     7    70       77     7000
## 8      X     8    80       88     8000
## 9      Y     9    90       99     9000
## 10     Y    10   100      110    10000</code></pre>
<pre class="r"><code>xx$Data1 &lt; 5 # which are less than 5</code></pre>
<pre><code>##  [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<pre class="r"><code>xx[xx$Data1 &lt; 5,]</code></pre>
<pre><code>##   Group Data1 Data2 NewData1 NewData2
## 1     X     1    10       11     1000
## 2     X     2    20       22     2000
## 3     Y     3    30       33     3000
## 4     Y     4    40       44     4000</code></pre>
<pre class="r"><code>xx[xx$Group == &quot;X&quot;, c(&quot;Group&quot;,&quot;Data2&quot;,&quot;NewData1&quot;)]</code></pre>
<pre><code>##   Group Data2 NewData1
## 1     X    10       11
## 2     X    20       22
## 6     X    60       66
## 7     X    70       77
## 8     X    80       88</code></pre>
<p>Data wrangling with <code>tidyverse</code> and pipes (<code>%&gt;%</code>)</p>
<pre class="r"><code>library(tidyverse) # install.packages(&quot;tidyverse&quot;)
xx &lt;- data.frame(Group = c(&quot;X&quot;,&quot;X&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;Y&quot;,&quot;X&quot;,&quot;X&quot;,&quot;X&quot;)) %&gt;%
  mutate(Data1 = 1:10, 
         Data2 = seq(10, 100, by = 10),
         NewData1 = Data1 + Data2,
         NewData2 = Data1 * 1000)
xx</code></pre>
<pre><code>##    Group Data1 Data2 NewData1 NewData2
## 1      X     1    10       11     1000
## 2      X     2    20       22     2000
## 3      Y     3    30       33     3000
## 4      Y     4    40       44     4000
## 5      Y     5    50       55     5000
## 6      Y     6    60       66     6000
## 7      Y     7    70       77     7000
## 8      X     8    80       88     8000
## 9      X     9    90       99     9000
## 10     X    10   100      110    10000</code></pre>
<pre class="r"><code>filter(xx, Data1 &lt; 5)</code></pre>
<pre><code>##   Group Data1 Data2 NewData1 NewData2
## 1     X     1    10       11     1000
## 2     X     2    20       22     2000
## 3     Y     3    30       33     3000
## 4     Y     4    40       44     4000</code></pre>
<pre class="r"><code>xx %&gt;% filter(Data1 &lt; 5)</code></pre>
<pre><code>##   Group Data1 Data2 NewData1 NewData2
## 1     X     1    10       11     1000
## 2     X     2    20       22     2000
## 3     Y     3    30       33     3000
## 4     Y     4    40       44     4000</code></pre>
<pre class="r"><code>xx %&gt;% filter(Group == &quot;X&quot;) %&gt;% 
  select(Group, NewColName=Data2, NewData1)</code></pre>
<pre><code>##   Group NewColName NewData1
## 1     X         10       11
## 2     X         20       22
## 3     X         80       88
## 4     X         90       99
## 5     X        100      110</code></pre>
<pre class="r"><code>xs &lt;- xx %&gt;% 
  group_by(Group) %&gt;% 
  summarise(Data2_mean = mean(Data2),
            Data2_sd = sd(Data2),
            NewData2_mean = mean(NewData2),
            NewData2_sd = sd(NewData2))
xs</code></pre>
<pre><code>## # A tibble: 2 x 5
##   Group Data2_mean Data2_sd NewData2_mean NewData2_sd
##   &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;
## 1 X             60     41.8          6000       4183.
## 2 Y             50     15.8          5000       1581.</code></pre>
<pre class="r"><code>xx %&gt;% left_join(xs, by = &quot;Group&quot;)</code></pre>
<pre><code>##    Group Data1 Data2 NewData1 NewData2 Data2_mean Data2_sd NewData2_mean
## 1      X     1    10       11     1000         60 41.83300          6000
## 2      X     2    20       22     2000         60 41.83300          6000
## 3      Y     3    30       33     3000         50 15.81139          5000
## 4      Y     4    40       44     4000         50 15.81139          5000
## 5      Y     5    50       55     5000         50 15.81139          5000
## 6      Y     6    60       66     6000         50 15.81139          5000
## 7      Y     7    70       77     7000         50 15.81139          5000
## 8      X     8    80       88     8000         60 41.83300          6000
## 9      X     9    90       99     9000         60 41.83300          6000
## 10     X    10   100      110    10000         60 41.83300          6000
##    NewData2_sd
## 1     4183.300
## 2     4183.300
## 3     1581.139
## 4     1581.139
## 5     1581.139
## 6     1581.139
## 7     1581.139
## 8     4183.300
## 9     4183.300
## 10    4183.300</code></pre>
</div>
<div id="readwrite-data" class="section level1">
<h1>Read/Write data</h1>
<pre class="r"><code>xx &lt;- read.csv(&quot;Data.csv&quot;)
write.csv(xx, &quot;Data.csv&quot;, row.names = F)</code></pre>
<p>For excel sheets, the package <code>readxl</code> can be used to read in sheets of data.</p>
<pre class="r"><code>library(readxl) # install.packages(&quot;readxl&quot;)
xx &lt;- read_xlsx(&quot;Data.xlsx&quot;, sheet = &quot;Data&quot;)</code></pre>
<div id="htmlwidget-1" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54"],["CDC Maxim AGL","ILL 618 AGL","Laird AGL","CDC Maxim AGL","Laird AGL","ILL 618 AGL","CDC Maxim AGL","Laird AGL","ILL 618 AGL","Laird AGL","CDC Maxim AGL","Laird AGL","ILL 618 AGL","ILL 618 AGL","CDC Maxim AGL","ILL 618 AGL","Laird AGL","CDC Maxim AGL","ILL 618 AGL","CDC Maxim AGL","ILL 618 AGL","ILL 618 AGL","CDC Maxim AGL","ILL 618 AGL","ILL 618 AGL","ILL 618 AGL","CDC Maxim AGL","Laird AGL","ILL 618 AGL","Laird AGL","ILL 618 AGL","CDC Maxim AGL","Laird AGL","CDC Maxim AGL","ILL 618 AGL","CDC Maxim AGL","ILL 618 AGL","Laird AGL","ILL 618 AGL","Laird AGL","CDC Maxim AGL","Laird AGL","CDC Maxim AGL","ILL 618 AGL","Laird AGL","CDC Maxim AGL","Laird AGL","Laird AGL","CDC Maxim AGL","Laird AGL","CDC Maxim AGL","Laird AGL","CDC Maxim AGL","Laird AGL"],["Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Metaponto, Italy","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Saskatoon, Canada","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh","Jessore, Bangladesh"],[2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2016,2016,2016,2016,2016,2016,2016,2016,2016,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017],[1,1,1,2,2,2,3,3,3,2,1,1,1,2,2,3,3,3,1,1,2,3,3,1,2,3,1,1,1,2,2,2,3,3,3,1,1,1,2,2,2,3,3,3,1,2,2,3,1,1,2,2,3,3],[128,135,133,133,135,135,128,130,135,56,50,56,47,48,51,47,56,51,48,55,46,46,53,84,82,80,139,139,139,146,142,139,138,138,141,84,76,73,77,74,83,74,85,77,60,55,57,56,88,78,90,78,90,84]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Name<\/th>\n      <th>Location<\/th>\n      <th>Year<\/th>\n      <th>Rep<\/th>\n      <th>DTF<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[3,4,5]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="tidy-data" class="section level1">
<h1>Tidy Data</h1>
<p><a href="https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html" class="uri">https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html</a></p>
<p><a href="https://r4ds.had.co.nz/tidy-data.html" class="uri">https://r4ds.had.co.nz/tidy-data.html</a></p>
<pre class="r"><code>yy &lt;- xx %&gt;%
  group_by(Name, Location) %&gt;%
  summarise(Mean_DTF = round(mean(DTF),1)) %&gt;% 
  arrange(Location)
yy</code></pre>
<pre><code>## # A tibble: 9 x 3
## # Groups:   Name [3]
##   Name          Location            Mean_DTF
##   &lt;chr&gt;         &lt;chr&gt;                  &lt;dbl&gt;
## 1 CDC Maxim AGL Jessore, Bangladesh     86.7
## 2 ILL 618 AGL   Jessore, Bangladesh     79.3
## 3 Laird AGL     Jessore, Bangladesh     76.8
## 4 CDC Maxim AGL Metaponto, Italy       134. 
## 5 ILL 618 AGL   Metaponto, Italy       138. 
## 6 Laird AGL     Metaponto, Italy       137. 
## 7 CDC Maxim AGL Saskatoon, Canada       52.5
## 8 ILL 618 AGL   Saskatoon, Canada       47  
## 9 Laird AGL     Saskatoon, Canada       56.8</code></pre>
<pre class="r"><code>yy &lt;- yy %&gt;% spread(key = Location, value = Mean_DTF)
yy</code></pre>
<pre><code>## # A tibble: 3 x 4
## # Groups:   Name [3]
##   Name          `Jessore, Bangladesh` `Metaponto, Italy` `Saskatoon, Canada`
##   &lt;chr&gt;                         &lt;dbl&gt;              &lt;dbl&gt;               &lt;dbl&gt;
## 1 CDC Maxim AGL                  86.7               134.                52.5
## 2 ILL 618 AGL                    79.3               138.                47  
## 3 Laird AGL                      76.8               137.                56.8</code></pre>
<pre class="r"><code>yy &lt;- yy %&gt;% gather(key = TraitName, value = Value, 2:4)
yy</code></pre>
<pre><code>## # A tibble: 9 x 3
## # Groups:   Name [3]
##   Name          TraitName           Value
##   &lt;chr&gt;         &lt;chr&gt;               &lt;dbl&gt;
## 1 CDC Maxim AGL Jessore, Bangladesh  86.7
## 2 ILL 618 AGL   Jessore, Bangladesh  79.3
## 3 Laird AGL     Jessore, Bangladesh  76.8
## 4 CDC Maxim AGL Metaponto, Italy    134. 
## 5 ILL 618 AGL   Metaponto, Italy    138. 
## 6 Laird AGL     Metaponto, Italy    137. 
## 7 CDC Maxim AGL Saskatoon, Canada    52.5
## 8 ILL 618 AGL   Saskatoon, Canada    47  
## 9 Laird AGL     Saskatoon, Canada    56.8</code></pre>
<pre class="r"><code>yy &lt;- yy %&gt;% spread(key = Name, value = Value)
yy</code></pre>
<pre><code>## # A tibble: 3 x 4
##   TraitName           `CDC Maxim AGL` `ILL 618 AGL` `Laird AGL`
##   &lt;chr&gt;                         &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;
## 1 Jessore, Bangladesh            86.7          79.3        76.8
## 2 Metaponto, Italy              134.          138.        137. 
## 3 Saskatoon, Canada              52.5          47          56.8</code></pre>
<hr />
</div>
<div id="base-plotting" class="section level1">
<h1>Base Plotting</h1>
<p>We will start with some basic plotting using the base function <code>plot()</code></p>
<p><a href="http://www.sthda.com/english/wiki/r-base-graphs" class="uri">http://www.sthda.com/english/wiki/r-base-graphs</a></p>
<p><a href="https://bookdown.org/rdpeng/exdata/the-base-plotting-system-1.html" class="uri">https://bookdown.org/rdpeng/exdata/the-base-plotting-system-1.html</a></p>
<pre class="r"><code># A basic scatter plot
plot(x = xd$x8, y = xd$x9)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<pre class="r"><code># Adjust color and shape of the points
plot(x = xd$x8, y = xd$x9, col = &quot;darkred&quot;, pch = 0)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-2.png" width="672" /></p>
<pre class="r"><code>plot(x = xd$x8, y = xd$x9, col = xd$x4, pch = xd$x4)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-3.png" width="672" /></p>
<pre class="r"><code># Adjust plot type 
plot(x = xd$x8, y = xd$x9, type = &quot;line&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-4.png" width="672" /></p>
<pre class="r"><code># Adjust linetype
plot(x = xd$x8, y = xd$x9, type = &quot;line&quot;, lty = 2)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-5.png" width="672" /></p>
<pre class="r"><code># Plot lines and points
plot(x = xd$x8, y = xd$x9, type = &quot;both&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-6.png" width="672" /></p>
<p>Now lets create some random and normally distributed data to make some more complicated plots</p>
<pre class="r"><code># 100 random uniformly distributed numbers ranging from 0 - 100
ru &lt;- runif(100, min = 0, max = 100)
ru</code></pre>
<pre><code>##   [1] 67.127346 84.219131  5.681644 66.126203 53.172840 18.788203 37.181698
##   [8] 19.026344 87.937164 30.598060 85.685840 84.072211 66.525072 41.523058
##  [15] 29.426085 72.803748 47.242782 81.763464 35.585022 62.670351 41.016284
##  [22] 18.941017 58.717911 99.905270 18.692365 84.759541 53.271362 91.317637
##  [29] 62.474599 91.026851  8.760138  8.760282 58.543937 53.610712 67.384256
##  [36] 50.794321 33.696345 88.224072 36.267128 85.776966 38.750369 68.693863
##  [43] 43.339740 90.752327 39.029789 68.261390 21.773096  7.587653 95.295279
##  [50]  0.929635 49.961330 93.270197 76.554851 64.655023 78.875630 30.776947
##  [57] 54.678297 53.472774  2.962598 20.107921 98.535729  2.262630 42.791770
##  [64] 42.833286 97.676412 33.262732 75.494385 14.222404 23.311284 48.110575
##  [71] 55.670151  3.305022 78.812653 90.473999 35.107893 26.586824 77.299194
##  [78] 60.045434 23.188872 33.118850  8.877511 72.562260 70.267509 61.565536
##  [85]  3.112638 31.710794 86.567488 90.395292 91.370389 41.559363 94.211068
##  [92]  9.382990 44.233474 25.224585 92.258729 80.760379 98.411611 48.405797
##  [99] 51.304789  2.051779</code></pre>
<pre class="r"><code>plot(x = ru)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>order(ru)</code></pre>
<pre><code>##   [1]  50 100  62  59  85  72   3  48  31  32  81  92  68  25   6  22   8  60
##  [19]  47  79  69  94  76  15  10  56  86  80  66  37  75  19  39   7  41  45
##  [37]  21  14  90  63  64  43  93  17  70  98  51  36  99   5  27  58  34  57
##  [55]  71  33  23  78  84  29  20  54   4  13   1  35  46  42  83  82  16  67
##  [73]  53  77  73  55  96  18  12   2  26  11  40  87   9  38  88  74  44  30
##  [91]  28  89  95  52  91  49  65  97  61  24</code></pre>
<pre class="r"><code>ru&lt;- ru[order(ru)]
ru</code></pre>
<pre><code>##   [1]  0.929635  2.051779  2.262630  2.962598  3.112638  3.305022  5.681644
##   [8]  7.587653  8.760138  8.760282  8.877511  9.382990 14.222404 18.692365
##  [15] 18.788203 18.941017 19.026344 20.107921 21.773096 23.188872 23.311284
##  [22] 25.224585 26.586824 29.426085 30.598060 30.776947 31.710794 33.118850
##  [29] 33.262732 33.696345 35.107893 35.585022 36.267128 37.181698 38.750369
##  [36] 39.029789 41.016284 41.523058 41.559363 42.791770 42.833286 43.339740
##  [43] 44.233474 47.242782 48.110575 48.405797 49.961330 50.794321 51.304789
##  [50] 53.172840 53.271362 53.472774 53.610712 54.678297 55.670151 58.543937
##  [57] 58.717911 60.045434 61.565536 62.474599 62.670351 64.655023 66.126203
##  [64] 66.525072 67.127346 67.384256 68.261390 68.693863 70.267509 72.562260
##  [71] 72.803748 75.494385 76.554851 77.299194 78.812653 78.875630 80.760379
##  [78] 81.763464 84.072211 84.219131 84.759541 85.685840 85.776966 86.567488
##  [85] 87.937164 88.224072 90.395292 90.473999 90.752327 91.026851 91.317637
##  [92] 91.370389 92.258729 93.270197 94.211068 95.295279 97.676412 98.411611
##  [99] 98.535729 99.905270</code></pre>
<pre class="r"><code>plot(x = ru)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<pre class="r"><code># 100 normally distributed numbers with a mean of 50 and sd of 10
nd &lt;- rnorm(100, mean = 50, sd = 10)
nd</code></pre>
<pre><code>##   [1] 55.44262 52.06645 41.76640 42.29078 44.93679 43.53793 71.96201 41.66591
##   [9] 57.36759 57.89932 42.62203 59.44051 44.46870 39.03609 60.88318 54.08978
##  [17] 48.09281 47.38762 57.17180 50.21622 53.73561 31.14777 37.73145 58.80449
##  [25] 52.65761 49.49071 36.31949 53.57009 48.91617 55.69520 42.66051 38.09309
##  [33] 38.96535 44.52822 49.76735 51.19161 60.56283 60.71448 44.16877 40.18333
##  [41] 41.85231 44.10811 56.10615 52.19212 49.19518 51.46685 56.01921 59.34732
##  [49] 55.36805 58.21876 41.58840 38.01548 62.93088 35.30106 52.49816 47.95631
##  [57] 72.59123 45.60752 33.48422 49.05552 49.22525 60.11482 57.66960 53.54627
##  [65] 53.03643 40.54016 65.64269 39.90045 57.14815 58.71818 47.62279 49.25133
##  [73] 47.74413 39.33089 55.26520 46.29423 53.97967 54.40953 62.69832 42.88777
##  [81] 41.38520 60.77473 58.51728 44.34208 44.93623 47.03241 45.98776 44.00739
##  [89] 59.96574 47.96543 42.99770 54.86176 50.44138 31.44444 43.91754 51.10454
##  [97] 57.18271 56.61141 40.19141 41.49059</code></pre>
<pre class="r"><code>nd &lt;- nd[order(nd)]
nd</code></pre>
<pre><code>##   [1] 31.14777 31.44444 33.48422 35.30106 36.31949 37.73145 38.01548 38.09309
##   [9] 38.96535 39.03609 39.33089 39.90045 40.18333 40.19141 40.54016 41.38520
##  [17] 41.49059 41.58840 41.66591 41.76640 41.85231 42.29078 42.62203 42.66051
##  [25] 42.88777 42.99770 43.53793 43.91754 44.00739 44.10811 44.16877 44.34208
##  [33] 44.46870 44.52822 44.93623 44.93679 45.60752 45.98776 46.29423 47.03241
##  [41] 47.38762 47.62279 47.74413 47.95631 47.96543 48.09281 48.91617 49.05552
##  [49] 49.19518 49.22525 49.25133 49.49071 49.76735 50.21622 50.44138 51.10454
##  [57] 51.19161 51.46685 52.06645 52.19212 52.49816 52.65761 53.03643 53.54627
##  [65] 53.57009 53.73561 53.97967 54.08978 54.40953 54.86176 55.26520 55.36805
##  [73] 55.44262 55.69520 56.01921 56.10615 56.61141 57.14815 57.17180 57.18271
##  [81] 57.36759 57.66960 57.89932 58.21876 58.51728 58.71818 58.80449 59.34732
##  [89] 59.44051 59.96574 60.11482 60.56283 60.71448 60.77473 60.88318 62.69832
##  [97] 62.93088 65.64269 71.96201 72.59123</code></pre>
<pre class="r"><code>plot(x = nd)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-3.png" width="672" /></p>
<pre class="r"><code>hist(x = nd)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-4.png" width="672" /></p>
<pre class="r"><code>hist(nd, breaks = 20, col = &quot;darkgreen&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-5.png" width="672" /></p>
<pre class="r"><code>plot(x = density(nd))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-6.png" width="672" /></p>
<pre class="r"><code>boxplot(x = nd)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-7.png" width="672" /></p>
<pre class="r"><code>boxplot(x = nd, horizontal = T)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-8.png" width="672" /></p>
</div>
<div id="ggplot2" class="section level1">
<h1>ggplot2</h1>
<p>Lets be honest, the base plots are ugly! The <code>ggplot2</code> package gives the user to create a better, more visually appealing plots. Additional packages such as <code>ggbeeswarm</code> and <code>ggrepel</code> also contain useful functions to add to the functionality of <code>ggplot2</code>.</p>
<p><a href="https://ggplot2.tidyverse.org/" class="uri">https://ggplot2.tidyverse.org/</a></p>
<p><a href="https://www.r-graph-gallery.com/ggplot2-package.html" class="uri">https://www.r-graph-gallery.com/ggplot2-package.html</a></p>
<p><a href="http://r-statistics.co/ggplot2-Tutorial-With-R.html" class="uri">http://r-statistics.co/ggplot2-Tutorial-With-R.html</a></p>
<p><a href="https://www.statsandr.com/blog/graphics-in-r-with-ggplot2/" class="uri">https://www.statsandr.com/blog/graphics-in-r-with-ggplot2/</a></p>
<pre class="r"><code>library(ggplot2)
mp &lt;- ggplot(xd, aes(x = x8, y = x9))
mp + geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code>mp + geom_point(aes(color = x3, shape = x3), size = 4)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<pre class="r"><code>mp + geom_line(size = 2)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-3.png" width="672" /></p>
<pre class="r"><code>mp + geom_line(aes(color = x3), size = 2)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-4.png" width="672" /></p>
<pre class="r"><code>mp + geom_smooth(method = &quot;loess&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-5.png" width="672" /></p>
<pre class="r"><code>mp + geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-6.png" width="672" /></p>
<pre class="r"><code>xx &lt;- data.frame(data = c(rnorm(50, mean = 40, sd = 10),
                          rnorm(50, mean = 60, sd = 5)),
                 group = factor(rep(1:2, each = 50)),
                 label = c(&quot;Label1&quot;, rep(NA, 49), &quot;Label2&quot;, rep(NA, 49)))
mp &lt;- ggplot(xx, aes(x = data, fill = group))
mp + geom_histogram(color = &quot;black&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-7.png" width="672" /></p>
<pre class="r"><code>mp + geom_histogram(color = &quot;black&quot;, position = &quot;dodge&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-8.png" width="672" /></p>
<pre class="r"><code>mp1 &lt;- mp + geom_histogram(color = &quot;black&quot;) + facet_grid(group~.)
mp1</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-9.png" width="672" /></p>
<pre class="r"><code>mp + geom_density(alpha = 0.5)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-10.png" width="672" /></p>
<pre class="r"><code>mp &lt;- ggplot(xx, aes(x = group, y = data, fill = group))
mp + geom_boxplot(color = &quot;black&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-11.png" width="672" /></p>
<pre class="r"><code>mp + geom_boxplot() + geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-12.png" width="672" /></p>
<pre class="r"><code>mp + geom_violin() + geom_boxplot(width = 0.1, fill = &quot;white&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-13.png" width="672" /></p>
<pre class="r"><code>library(ggbeeswarm)
mp + geom_quasirandom()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-14.png" width="672" /></p>
<pre class="r"><code>mp + geom_quasirandom(aes(shape = group))</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-15.png" width="672" /></p>
<pre class="r"><code>mp2 &lt;- mp + geom_violin() + 
  geom_boxplot(width = 0.1, fill = &quot;white&quot;) +
  geom_beeswarm(alpha = 0.5)
library(ggrepel)
mp2 + geom_text_repel(aes(label = label), nudge_x = 0.4)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-16.png" width="672" /></p>
<pre class="r"><code>library(ggpubr)
ggarrange(mp1, mp2, ncol = 2, widths = c(2,1),
          common.legend = T, legend = &quot;bottom&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-17.png" width="672" /></p>
<hr />
</div>
<div id="statistics" class="section level1">
<h1>Statistics</h1>
<p><a href="http://biostathandbook.com/" class="uri">http://biostathandbook.com/</a></p>
<p><a href="https://rcompanion.org/rcompanion/a_02.html" class="uri">https://rcompanion.org/rcompanion/a_02.html</a></p>
<pre class="r"><code># Prep data
lev_Loc  &lt;- c(&quot;Saskatoon, Canada&quot;, &quot;Jessore, Bangladesh&quot;, &quot;Metaponto, Italy&quot;)
lev_Name &lt;- c(&quot;ILL 618 AGL&quot;, &quot;CDC Maxim AGL&quot;, &quot;Laird AGL&quot;)
dd &lt;- read_xlsx(&quot;Data.xlsx&quot;, sheet = &quot;Data&quot;) %&gt;%
  mutate(Location = factor(Location, levels = lev_Loc),
         Name = factor(Name, levels = lev_Name))
xx &lt;- dd %&gt;%
  group_by(Name, Location) %&gt;%
  summarise(Mean_DTF = mean(DTF))
xx %&gt;% spread(Location, Mean_DTF)</code></pre>
<pre><code>## # A tibble: 3 x 4
## # Groups:   Name [3]
##   Name          `Saskatoon, Canada` `Jessore, Bangladesh` `Metaponto, Italy`
##   &lt;fct&gt;                       &lt;dbl&gt;                 &lt;dbl&gt;              &lt;dbl&gt;
## 1 ILL 618 AGL                  47                    79.3               138.
## 2 CDC Maxim AGL                52.5                  86.7               134.
## 3 Laird AGL                    56.8                  76.8               137.</code></pre>
<pre class="r"><code># Plot
mp1 &lt;- ggplot(dd, aes(x = Location, y = DTF, color = Name, shape = Name)) +
  geom_point(size = 2, alpha = 0.7, position = position_dodge(width=0.5))
mp2 &lt;- ggplot(xx, aes(x = Location, y = Mean_DTF, color = Name, group = Name, shape = Name)) +
  geom_point(size = 2.5, alpha = 0.7) + 
  geom_line(size = 1, alpha = 0.7) +
  theme(legend.position = &quot;top&quot;)
ggarrange(mp1, mp2, ncol = 2, common.legend = T, legend = &quot;top&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>From first glace, it is clear there are differences between genotypes, locations, and genotype x environment (GxE) interactions. Now let’s do a few statistical tests.</p>
<pre class="r"><code>summary(aov(DTF ~ Name * Location, data = dd))</code></pre>
<pre><code>##               Df Sum Sq Mean Sq  F value   Pr(&gt;F)    
## Name           2     88      44    3.476   0.0395 *  
## Location       2  65863   32932 2598.336  &lt; 2e-16 ***
## Name:Location  4    560     140   11.044 2.52e-06 ***
## Residuals     45    570      13                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As expected, an ANOVA shows statistical significance for genotype (p-value = 0.0395), Location (p-value &lt; 2e-16) and GxE interactions (p-value &lt; 2.52e-06). However, all this tells us is that one genotype is different from the rest, one location is different from the others and that there is GxE interactions. If we want to be more specific, we can filter the data and perform say a <em>t-test</em> to compare two groups.</p>
<pre class="r"><code>xx &lt;- dd %&gt;% 
  filter(Location %in% c(&quot;Saskatoon, Canada&quot;, &quot;Jessore, Bangladesh&quot;)) %&gt;%
  spread(Location, DTF)
t.test(x = xx$`Saskatoon, Canada`, y = xx$`Jessore, Bangladesh`)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  xx$`Saskatoon, Canada` and xx$`Jessore, Bangladesh`
## t = -17.521, df = 32.701, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -32.18265 -25.48402
## sample estimates:
## mean of x mean of y 
##  52.11111  80.94444</code></pre>
<p>DTF in Saskatoon, Canada is significantly different (p-value &lt; 2.2e-16) from DTF in Jessore, Bangladesh.</p>
<pre class="r"><code>xx &lt;- dd %&gt;% 
  filter(Name %in% c(&quot;ILL 618 AGL&quot;, &quot;Laird AGL&quot;),
         Location == &quot;Metaponto, Italy&quot;) %&gt;%
  spread(Name, DTF)
t.test(x = xx$`ILL 618 AGL`, y = xx$`Laird AGL`)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  xx$`ILL 618 AGL` and xx$`Laird AGL`
## t = 0.38008, df = 8.0564, p-value = 0.7137
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.059739  7.059739
## sample estimates:
## mean of x mean of y 
##  137.8333  136.8333</code></pre>
<p>DTF between ILL 618 AGL and Laird AGL are not significantly different (p-value = 0.7137) in Metaponto, Italy.</p>
<hr />
</div>
<div id="pch-plot" class="section level1">
<h1>pch Plot</h1>
<pre class="r"><code>xx &lt;- data.frame(x = rep(1:6, times = 5, length.out = 26),
                 y = rep(5:1, each = 6, length.out = 26),
                 pch = 0:25)
mp &lt;- ggplot(xx, aes(x = x, y = y, shape = as.factor(pch))) +
  geom_point(color = &quot;darkred&quot;, fill = &quot;darkblue&quot;, size = 5) +
  geom_text(aes(label = pch), nudge_x = -0.25) +
  scale_shape_manual(values = xx$pch) +
  scale_x_continuous(breaks = 6:1) +
  scale_y_continuous(breaks = 6:1) +
  theme_void() +
  theme(legend.position = &quot;none&quot;,
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(title = &quot;Plot symbols in R (pch)&quot;,
       subtitle = &quot;color = \&quot;darkred\&quot;, fill = \&quot;darkblue\&quot;&quot;,
       x = NULL, y = NULL)
ggsave(&quot;pch.png&quot;, mp, width = 4.5, height = 3)</code></pre>
<p><img src="pch.png" /></p>
<hr />
</div>
<div id="r-markdown" class="section level1">
<h1>R Markdown</h1>
<p>Tutorials on how to create an R markdown document like this one can be found here:</p>
<ul>
<li><a href="https://rmarkdown.rstudio.com/articles_intro.html" class="uri">https://rmarkdown.rstudio.com/articles_intro.html</a></li>
<li><a href="https://rmarkdown.rstudio.com/lesson-1.html" class="uri">https://rmarkdown.rstudio.com/lesson-1.html</a></li>
<li><a href="https://alexd106.github.io/intro2R/Rmarkdown_intro.html" class="uri">https://alexd106.github.io/intro2R/Rmarkdown_intro.html</a></li>
</ul>
<hr />
<p>© Derek Michael Wright 2020 <a href="https://dblogr.netlify.com/">www.dblogr.com/</a></p>
</div>
