---
title: "Lentil GWAS Phenology"
summary:  "**Focusing the GWAS *Lens* on days to flower using latent variable phenotypes derived from global multi-environment trials**. *The Plant Genome*. (2022) e20269."
date: "`r Sys.Date()`"
author: "Derek Michael Wright <derek.wright@usask.ca> [www.dblogr.com/](https://dblogr.com/#posts_academic)"
tags: [ "Publications", "AGILE", "Lentil", "Genomics", "Phenomics", "Phenology", "Featured" ]
weight: 1
links:
  - icon: "newspaper"
    icon_pack: "far"
    name: "The Plant Genome. (2022) e20269."
    url: "https://doi.org/10.1002/tpg2.20269"
  - icon: "github"
    icon_pack: "fab"
    name: "Github Repository"
    url: "https://github.com/derekmichaelwright/AGILE_LDP_GWAS_Phenology"
  - icon: "chart-line"
    icon_pack: "fas"
    name: "All Figures (HTML)"
    url: "https://derekmichaelwright.github.io/AGILE_LDP_GWAS_Phenology/README.html"
  - icon: "file-pdf"
    icon_pack: "far"
    name: "All Figures (pdf)"
    url: "https://github.com/derekmichaelwright/AGILE_LDP_GWAS_Phenology/blob/master/README.pdf"
  - icon: "r-project"
    icon_pack: "fab"
    name: "R Script (HTML)"
    url: "https://derekmichaelwright.github.io/AGILE_LDP_GWAS_Phenology/GWAS_Phenology_Vignette.html"
external_link: "https://doi.org/10.1002/tpg2.20269"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

---

# Citation

Sandesh Neupane, Derek M Wright, Jakob Butler, Raul Martinez, Jim Weller, Kirstin E Bett (2022) **Focusing the GWAS Lens on days to flower using latent variable phenotypes derived from global multi-environment trials**. *The Plant Genome*. e20269. https://doi.org/10.1002/tpg2.20269

---

# Abstract

Adaptation constraints within crop species have resulted in limited genetic diversity in some breeding programs and/or areas where new crops have been introduced, e.g., lentil (Lens culinaris Medik.) in North America. An improved understanding of the underlying genetics involved in phenology-related traits is valuable knowledge to aid breeders in overcoming limitations associated with unadapted germplasm and expanding their genetic diversity by introducing new, exotic material. We used a large, 18 site-year, multi-environment dataset, phenotyped for phenology-related traits across nine locations and over three years, along with accompanying latent variable phenotypes derived from a photothermal model and principal component analysis (PCA) of days from sowing to flower (DTF) data for a lentil diversity panel (324 accessions) which has also been genotyped with an exome capture array. Genome-wide association studies (GWAS) on DTF across multiple environments helped confirm associations with known flowering time genes and identify new quantitative trait loci (QTL), which may contain previously unknown flowering time genes. Additionally, the use of latent variable phenotypes, which can incorporate environmental data such as temperature and photoperiod as both GWAS traits and as covariates, strengthened associations, revealed additional hidden associations, and alluded to potential roles of the associated QTL. Our approach can be replicated with other crop species, and the results from our GWAS serve as a resource for further exploration into the complex nature of phenology-related traits across the major growing environments for cultivated lentil.

---

Derek Michael Wright [www.dblogr.com/](https://dblogr.com/)