---
title: "Photography Appender"
subtitle: "create featured.png for each photoalbum page"
date: "Last updated: `r Sys.Date()`"
author: "Derek Michael Wright [www.dblogr.com/](http://dblogr.com/) or [derekmichaelwright.github.io/dblogr](https://derekmichaelwright.github.io/dblogr/) <derek.wright@usask.ca>"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r echo = F}
library(magick)
```

---

## AGILE

```{r echo = F}
folder <- "agile/02flowers/"
xx <- list.files(folder)[1:9]
xx <- paste0(folder, xx)
ims <- image_read(xx) %>% image_scale("250x250") %>%
  image_border("black", "3x3")
im <- image_append(c(image_append(ims[1:3]),
                     image_append(ims[4:6]),
                     image_append(ims[7:9]) ), stack = TRUE)
image_write(im, path = paste0("agile/featured.png"), format = "png")
```

---

## General

```{r echo = F}
folder <- "general/01street/"
xx <- list.files(folder)[1:9]
xx <- paste0(folder, xx)
ims <- image_read(xx) %>% image_scale("250x250") %>%
  image_border("black", "3x3")
im <- image_append(c(image_append(ims[1:3]),
                     image_append(ims[4:6]),
                     image_append(ims[7:9]) ), stack = TRUE)
image_write(im, path = paste0("general/featured.png"), format = "png")
```

---

## Mountains

```{r echo = F}
folder <- "mountains/05colorado/"
xx <- list.files(folder)[1:9]
xx <- paste0(folder, xx)
ims <- image_read(xx) %>% image_scale("250x250") %>%
  image_border("black", "3x3")
im <- image_append(c(image_append(ims[1:3]),
                     image_append(ims[4:6]),
                     image_append(ims[7:9]) ), stack = TRUE)
image_write(im, path = paste0("mountains/featured.png"), format = "png")
```

---

## Saskatchewan

```{r echo = F}
folder <- "saskatchewan/01katepwa/"
xx <- list.files(folder)[1:9]
xx <- paste0(folder, xx)
ims <- image_read(xx) %>% image_scale("250x250") %>%
  image_border("black", "3x3")
im <- image_append(c(image_append(ims[1:3]),
                     image_append(ims[4:6]),
                     image_append(ims[7:9]) ), stack = TRUE)
image_write(im, path = paste0("saskatchewan/featured.png"), format = "png")
```

---
