---
title: "AGILE Photography"
subtitle: "Some of my work photography at the U of S"
date: "Last updated: `r Sys.Date()`"
author: "Derek Michael Wright [derekmichaelwright.github.io/dblogr](https://derekmichaelwright.github.io/dblogr/) <derek.wright@usask.ca>"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r echo = F}
#devtools::install_github("royfrancis/pixture")
library(pixture)
library(stringr)
#pixgallery(paste0("fold/", list.files("fold/")), layout = "justified") 
# "masonry", "justified", 
# "grid", "fixed", "mosaic", "masonry", "justified", "elastic" or "rhombus"
```

---

# Flowers

```{r echo = F}
xF_02 <- "02flowers/"
xN_02 <- list.files(xF_02)
xL_02 <- paste0(xF_02, xN_02)
xC_02 <- paste("Image", 
                str_pad(1:(length(xN_02)), width = 3, pad = "0"),
                "-", xN_02)
pixgallery(path = xL_02, layout = "masonry")
```

---

# Pods

```{r echo = F}
xF_03 <- "03pods/"
xN_03 <- list.files(xF_03)
xL_03 <- paste0(xF_03, xN_03)
xC_03 <- paste("Image", 
                str_pad(1:(length(xN_03)), width = 3, pad = "0"),
                "-", xN_03)
pixgallery(path = xL_03, layout = "masonry")
```

---

## Emergence

```{r echo = F}
xF_01 <- "01emergence/"
xN_01 <- list.files(xF_01)
xL_01 <- paste0(xF_01, xN_01)
xC_01 <- paste("Image", 
                str_pad(1:(length(xN_01)), width = 3, pad = "0"),
                "-", xN_01)
pixgallery(path = xL_01, layout = "masonry")
```
