---
title: "Nepal Lentil Phenology"
subtitle: "**Strategic Identification of New Genetic Diversity to Expand Lentil (*Lens culinaris* Medik.) Production (Using Nepal as an Example)**. *Agronomy*. (2021) 11(10): 1933."
summary:  "**Strategic Identification of New Genetic Diversity to Expand Lentil (*Lens culinaris* Medik.) Production (Using Nepal as an Example)**. *Agronomy*. (2021) 11(10): 1933."
author: "Derek Michael Wright <derek.wright@usask.ca> [www.dblogr.com/](https://dblogr.com/#posts_academic)"
date: "`r Sys.Date()`"
tags: [ "Publications", "AGILE", "Lentil", "Phenomics", "Phenology" ]
math: true
weight: 2
links:
  - icon: "newspaper"
    icon_pack: "far"
    name: "Agronomy. (2021) 11(10): 1933."
    url: "https://doi.org/10.3390/agronomy11101933"
  - icon: "r-project"
    icon_pack: "fab"
    name: "R Script (HTML)"
    url: "https://derekmichaelwright.github.io/AGILE_LDP_Nepal/Phenology_Vignette.html"
external_link: "https://doi.org/10.3390/agronomy11101933"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

---

# Citation

Neupane S., Dhakal R., Wright D.M., Shrestha D.K., Dhakal B., Bett K.E. (**2021**) Strategic Identification of New Genetic Diversity to Expand Lentil (*Lens culinaris* Medik.) Production (Using Nepal as an Example). *Agronomy*. 11(10): 1933.
https://doi.org/10.3390/agronomy11101933

---

# Abstract

Although lentil has a long history of cultivation, cultivars rely on a narrow genetic base, indicating room for broadening the diversity. Two field experiments were conducted at Bardiya, Nepal, during winter 2016 and 2017, with 324 diverse lentil genotypes obtained from genebanks and breeding programs around the world. Phenological traits related to adaptation, particularly days to flower, were assessed. A photothermal model was used to predict days to flower in new environments to identify genotypes that may be suitable for additional growing regions in Nepal, allowing for the expansion of the production area. Many putatively adapted genotypes were identified for terai, mid-hill, and high-hill growing regions. The list includes large-seeded or yellow cotyledon lines, representing new market classes of lentils for Nepal.

---

Derek Michael Wright [www.dblogr.com/](https://dblogr.com/)